; LLVM IR generated by compiler
target triple = "x86_64-w64-windows-gnu"

; module math
define i32 @add(i32 %p0, i32 %p1) {
entry:
  %r0 = alloca i32
  store i32 %p0, ptr %r0
  %r1 = alloca i32
  store i32 %p1, ptr %r1
  %r2 = load i32, ptr %r0
  %r3 = load i32, ptr %r1
  %r4 = add i32 %r2, %r3
  ret i32 %r4
}

define i32 @main() {
entry:
  %r0 = add i32 0, 2
  %r1 = add i32 0, 3
  %r2 = call i32 @add(i32 %r0, i32 %r1)
  ret i32 %r2
}

